### ISSUE TITLE
Nothing happens when I run npx @angular/cli new app-name --routing

### ISSUE THREAD

**Issue by CRTISIT** [duluca/local-weather-app#18]
Hi there, I have been following along in the book, did everything exactly as mentioned. I am just in chapter 2 now. And you said to run this command 
npx @angular/cli new app-name --routing

When I do that, nothing happens on the screen (it is supposed to create a bunch of files). It doesnt even create a directory or any files, etc. No error messages are given either.  I ran a command to see if I have any global packages installed, and nothing is installed globally.  So I am not sure why this command is not working npx @angular/cli new app-name --routing

However, I was looking up stuff on google, and saw this command, so I tried it:
npx create-react-app my-app

and that worked fine. It created the directories, and files. And then I changed into my-app folder and then typed npm start....and it worked. I saw the basic react app.

Do you have any suggestions as to what I can do at this point? I am really bummed out that the first time I get to do real coding, that this command is not doing anything
npx @angular/cli new app-name --routing

PS On page 32 of the book is where I am at. And I am wondering, am I already supposed to have @anglular/cli installed before running the command npx @angular/cli new app-name --routing

Maybe I was supposed to install @angular/cli already, and I did not see that mentioned in your book.
 
EDIT: After googling some more, I tried this and it seems to work. But is this doing the same result as what you wrote on page 32 of the book?
    npx -p @angular/cli ng new local-weather-app

After running that command, I have a working project I can run with npm start

**Comment by duluca** [comment]
@CRTISIT That is odd. I've never seen that happen before and I'm sorry it didn't work for you the first time. Regardless, great find with the work-around. I updated the project readme with that information! Thanks for the report.
