### ISSUE TITLE
Chapter 4 Code Examples - Already Fixed - Angular for Enterprise-Ready Web Applications

### ISSUE THREAD

**Issue by yogibear** [duluca/local-weather-app#537]
Currently working my way through the _Angular for Enterprise-Ready Web Applications_ book.

It Chapter 4 it talks about the failing tests in projects/ch4 and the goes on to walk you through how to fix them and educate you on various related aspects as it does so.

Problem is all the 14 tests pass first time. Chapter 4 becomes more theoretical and less practical. This is a shame.

**Comment by AlexandreCH** [comment]
For e2e tests, try to install protractor and webdriver-manager : npm install -g protractor
