### ISSUE TITLE
Impossible to run stage 5

### ISSUE THREAD

**Issue by Atyzeph** [duluca/local-weather-app#989]
I try to run the npm start command for the first time in chapter 2 but I have the impression that I only have stage 6 which is executed and I can't do anything else ...

Am I misunderstanding something ?

**Comment by duluca** [comment]
@Atyzeph By default `npm start` will only act on the root project. To execute a stage you must specify the project (stage) name. 

You can either use `ng serve stage5` or `npx ng serve stage5`
Alternatively, you can pass the project name to the `npm start` command. 
This would look like: 
`npm start -- stage5`
